"""
ISO/IEC 27001:2022 Annex A control library.

93 controls across 4 themes, restructured from the 114 controls of the
2013 edition. Each entry is:

    (reference, theme, title, control_type, purpose)

Control type follows the ISO/IEC 27002:2022 attribute of the same name.
"""

ORGANIZATIONAL = "Organizational"
PEOPLE = "People"
PHYSICAL = "Physical"
TECHNOLOGICAL = "Technological"

PREVENTIVE = "Preventive"
DETECTIVE = "Detective"
CORRECTIVE = "Corrective"

CONTROLS = [
    # ---------------------------------------------------------------- A.5
    ("A.5.1", ORGANIZATIONAL, "Policies for information security", PREVENTIVE,
     "Define, approve, publish and review a set of information security policies."),
    ("A.5.2", ORGANIZATIONAL, "Information security roles and responsibilities", PREVENTIVE,
     "Define and allocate information security responsibilities across the organisation."),
    ("A.5.3", ORGANIZATIONAL, "Segregation of duties", PREVENTIVE,
     "Separate conflicting duties to reduce the risk of fraud, error and misuse."),
    ("A.5.4", ORGANIZATIONAL, "Management responsibilities", PREVENTIVE,
     "Require all personnel to apply information security per established policy."),
    ("A.5.5", ORGANIZATIONAL, "Contact with authorities", PREVENTIVE,
     "Maintain contact with relevant authorities such as CERT-In and law enforcement."),
    ("A.5.6", ORGANIZATIONAL, "Contact with special interest groups", PREVENTIVE,
     "Maintain contact with security forums and professional associations."),
    ("A.5.7", ORGANIZATIONAL, "Threat intelligence", DETECTIVE,
     "Collect and analyse threat information to produce actionable intelligence."),
    ("A.5.8", ORGANIZATIONAL, "Information security in project management", PREVENTIVE,
     "Integrate information security into project management practices."),
    ("A.5.9", ORGANIZATIONAL, "Inventory of information and other associated assets", PREVENTIVE,
     "Develop and maintain an inventory of information assets with assigned owners."),
    ("A.5.10", ORGANIZATIONAL, "Acceptable use of information and other associated assets", PREVENTIVE,
     "Identify and document rules for acceptable use of information and assets."),
    ("A.5.11", ORGANIZATIONAL, "Return of assets", PREVENTIVE,
     "Ensure personnel return organisational assets on termination or change of role."),
    ("A.5.12", ORGANIZATIONAL, "Classification of information", PREVENTIVE,
     "Classify information according to confidentiality, integrity and availability needs."),
    ("A.5.13", ORGANIZATIONAL, "Labelling of information", PREVENTIVE,
     "Apply labelling procedures in line with the classification scheme."),
    ("A.5.14", ORGANIZATIONAL, "Information transfer", PREVENTIVE,
     "Put rules and agreements in place for all types of information transfer."),
    ("A.5.15", ORGANIZATIONAL, "Access control", PREVENTIVE,
     "Establish rules to control physical and logical access to information."),
    ("A.5.16", ORGANIZATIONAL, "Identity management", PREVENTIVE,
     "Manage the full lifecycle of identities used to access the organisation's systems."),
    ("A.5.17", ORGANIZATIONAL, "Authentication information", PREVENTIVE,
     "Control allocation and management of passwords and other authentication secrets."),
    ("A.5.18", ORGANIZATIONAL, "Access rights", PREVENTIVE,
     "Provision, review, modify and remove access rights per the access control policy."),
    ("A.5.19", ORGANIZATIONAL, "Information security in supplier relationships", PREVENTIVE,
     "Manage the security risks associated with the use of supplier products and services."),
    ("A.5.20", ORGANIZATIONAL, "Addressing information security within supplier agreements", PREVENTIVE,
     "Establish and agree security requirements with each supplier."),
    ("A.5.21", ORGANIZATIONAL, "Managing information security in the ICT supply chain", PREVENTIVE,
     "Manage security risks across the ICT products and services supply chain."),
    ("A.5.22", ORGANIZATIONAL, "Monitoring, review and change management of supplier services", DETECTIVE,
     "Regularly monitor and audit supplier service delivery and manage changes."),
    ("A.5.23", ORGANIZATIONAL, "Information security for use of cloud services", PREVENTIVE,
     "Define processes for acquisition, use, management and exit of cloud services."),
    ("A.5.24", ORGANIZATIONAL, "Information security incident management planning and preparation", CORRECTIVE,
     "Plan and prepare for incident management by defining roles and processes."),
    ("A.5.25", ORGANIZATIONAL, "Assessment and decision on information security events", DETECTIVE,
     "Assess security events and decide whether they are security incidents."),
    ("A.5.26", ORGANIZATIONAL, "Response to information security incidents", CORRECTIVE,
     "Respond to incidents in accordance with documented procedures."),
    ("A.5.27", ORGANIZATIONAL, "Learning from information security incidents", PREVENTIVE,
     "Use knowledge from incidents to strengthen controls."),
    ("A.5.28", ORGANIZATIONAL, "Collection of evidence", CORRECTIVE,
     "Establish procedures for identification, collection and preservation of evidence."),
    ("A.5.29", ORGANIZATIONAL, "Information security during disruption", PREVENTIVE,
     "Maintain information security at an appropriate level during disruption."),
    ("A.5.30", ORGANIZATIONAL, "ICT readiness for business continuity", CORRECTIVE,
     "Plan, implement and test ICT readiness based on business continuity objectives."),
    ("A.5.31", ORGANIZATIONAL, "Legal, statutory, regulatory and contractual requirements", PREVENTIVE,
     "Identify and document all legal and contractual security obligations."),
    ("A.5.32", ORGANIZATIONAL, "Intellectual property rights", PREVENTIVE,
     "Protect intellectual property rights, including software licensing compliance."),
    ("A.5.33", ORGANIZATIONAL, "Protection of records", PREVENTIVE,
     "Protect records from loss, destruction, falsification and unauthorised access."),
    ("A.5.34", ORGANIZATIONAL, "Privacy and protection of PII", PREVENTIVE,
     "Identify and meet requirements for the protection of personally identifiable information."),
    ("A.5.35", ORGANIZATIONAL, "Independent review of information security", DETECTIVE,
     "Review the organisation's approach to information security independently and periodically."),
    ("A.5.36", ORGANIZATIONAL, "Compliance with policies, rules and standards for information security", DETECTIVE,
     "Regularly review compliance with the information security policy set."),
    ("A.5.37", ORGANIZATIONAL, "Documented operating procedures", PREVENTIVE,
     "Document operating procedures for information processing facilities."),

    # ---------------------------------------------------------------- A.6
    ("A.6.1", PEOPLE, "Screening", PREVENTIVE,
     "Carry out background verification checks on candidates before employment."),
    ("A.6.2", PEOPLE, "Terms and conditions of employment", PREVENTIVE,
     "State information security responsibilities in employment contracts."),
    ("A.6.3", PEOPLE, "Information security awareness, education and training", PREVENTIVE,
     "Provide regular security awareness training relevant to each job role."),
    ("A.6.4", PEOPLE, "Disciplinary process", CORRECTIVE,
     "Formalise and communicate a disciplinary process for security policy violations."),
    ("A.6.5", PEOPLE, "Responsibilities after termination or change of employment", PREVENTIVE,
     "Define and enforce security duties that remain valid after employment ends."),
    ("A.6.6", PEOPLE, "Confidentiality or non-disclosure agreements", PREVENTIVE,
     "Identify, document and regularly review confidentiality and NDA requirements."),
    ("A.6.7", PEOPLE, "Remote working", PREVENTIVE,
     "Implement security measures for personnel working outside company premises."),
    ("A.6.8", PEOPLE, "Information security event reporting", DETECTIVE,
     "Provide a mechanism for personnel to report observed security events promptly."),

    # ---------------------------------------------------------------- A.7
    ("A.7.1", PHYSICAL, "Physical security perimeters", PREVENTIVE,
     "Define and use security perimeters to protect areas containing information assets."),
    ("A.7.2", PHYSICAL, "Physical entry", PREVENTIVE,
     "Protect secure areas by appropriate entry controls and access points."),
    ("A.7.3", PHYSICAL, "Securing offices, rooms and facilities", PREVENTIVE,
     "Design and apply physical security for offices, rooms and facilities."),
    ("A.7.4", PHYSICAL, "Physical security monitoring", DETECTIVE,
     "Continuously monitor premises for unauthorised physical access."),
    ("A.7.5", PHYSICAL, "Protecting against physical and environmental threats", PREVENTIVE,
     "Design protection against fire, flood, and other natural or man-made threats."),
    ("A.7.6", PHYSICAL, "Working in secure areas", PREVENTIVE,
     "Design and apply security measures for working in secure areas."),
    ("A.7.7", PHYSICAL, "Clear desk and clear screen", PREVENTIVE,
     "Enforce clear desk and clear screen rules for information processing facilities."),
    ("A.7.8", PHYSICAL, "Equipment siting and protection", PREVENTIVE,
     "Site and protect equipment to reduce environmental and unauthorised access risks."),
    ("A.7.9", PHYSICAL, "Security of assets off-premises", PREVENTIVE,
     "Protect off-site assets such as laptops carried by field and sales staff."),
    ("A.7.10", PHYSICAL, "Storage media", PREVENTIVE,
     "Manage storage media through their lifecycle of acquisition, use, transport and disposal."),
    ("A.7.11", PHYSICAL, "Supporting utilities", PREVENTIVE,
     "Protect facilities from power failures and other utility disruptions."),
    ("A.7.12", PHYSICAL, "Cabling security", PREVENTIVE,
     "Protect power and telecommunications cabling from interception and damage."),
    ("A.7.13", PHYSICAL, "Equipment maintenance", PREVENTIVE,
     "Maintain equipment correctly to ensure availability and integrity of information."),
    ("A.7.14", PHYSICAL, "Secure disposal or re-use of equipment", PREVENTIVE,
     "Verify removal or secure overwriting of data before disposal or re-use."),

    # ---------------------------------------------------------------- A.8
    ("A.8.1", TECHNOLOGICAL, "User endpoint devices", PREVENTIVE,
     "Protect information stored on, processed by or accessible via user endpoint devices."),
    ("A.8.2", TECHNOLOGICAL, "Privileged access rights", PREVENTIVE,
     "Restrict and manage the allocation and use of privileged access rights."),
    ("A.8.3", TECHNOLOGICAL, "Information access restriction", PREVENTIVE,
     "Restrict access to information and application functions per the access control policy."),
    ("A.8.4", TECHNOLOGICAL, "Access to source code", PREVENTIVE,
     "Appropriately manage read and write access to source code and development tools."),
    ("A.8.5", TECHNOLOGICAL, "Secure authentication", PREVENTIVE,
     "Implement secure authentication technologies such as multi-factor authentication."),
    ("A.8.6", TECHNOLOGICAL, "Capacity management", PREVENTIVE,
     "Monitor and tune the use of resources in line with capacity requirements."),
    ("A.8.7", TECHNOLOGICAL, "Protection against malware", PREVENTIVE,
     "Implement malware protection supported by user awareness."),
    ("A.8.8", TECHNOLOGICAL, "Management of technical vulnerabilities", PREVENTIVE,
     "Obtain information about technical vulnerabilities and take appropriate action."),
    ("A.8.9", TECHNOLOGICAL, "Configuration management", PREVENTIVE,
     "Establish, document, implement, monitor and review configurations of assets."),
    ("A.8.10", TECHNOLOGICAL, "Information deletion", PREVENTIVE,
     "Delete information when no longer required to limit unnecessary disclosure."),
    ("A.8.11", TECHNOLOGICAL, "Data masking", PREVENTIVE,
     "Use data masking in line with access control and business requirements."),
    ("A.8.12", TECHNOLOGICAL, "Data leakage prevention", PREVENTIVE,
     "Apply data leakage prevention measures to systems handling sensitive information."),
    ("A.8.13", TECHNOLOGICAL, "Information backup", CORRECTIVE,
     "Maintain and regularly test backups of information, software and systems."),
    ("A.8.14", TECHNOLOGICAL, "Redundancy of information processing facilities", PREVENTIVE,
     "Implement redundancy sufficient to meet availability requirements."),
    ("A.8.15", TECHNOLOGICAL, "Logging", DETECTIVE,
     "Produce, store, protect and analyse logs of activities and security events."),
    ("A.8.16", TECHNOLOGICAL, "Monitoring activities", DETECTIVE,
     "Monitor networks, systems and applications for anomalous behaviour."),
    ("A.8.17", TECHNOLOGICAL, "Clock synchronisation", DETECTIVE,
     "Synchronise system clocks to an approved reference time source."),
    ("A.8.18", TECHNOLOGICAL, "Use of privileged utility programs", PREVENTIVE,
     "Restrict and tightly control utility programs capable of overriding controls."),
    ("A.8.19", TECHNOLOGICAL, "Installation of software on operational systems", PREVENTIVE,
     "Implement procedures to securely manage software installation on live systems."),
    ("A.8.20", TECHNOLOGICAL, "Networks security", PREVENTIVE,
     "Secure, manage and control networks to protect information in systems."),
    ("A.8.21", TECHNOLOGICAL, "Security of network services", PREVENTIVE,
     "Identify and include security mechanisms and service levels for network services."),
    ("A.8.22", TECHNOLOGICAL, "Segregation of networks", PREVENTIVE,
     "Segregate groups of information services, users and systems on the network."),
    ("A.8.23", TECHNOLOGICAL, "Web filtering", PREVENTIVE,
     "Manage access to external websites to reduce exposure to malicious content."),
    ("A.8.24", TECHNOLOGICAL, "Use of cryptography", PREVENTIVE,
     "Define and implement rules for effective use of cryptography and key management."),
    ("A.8.25", TECHNOLOGICAL, "Secure development life cycle", PREVENTIVE,
     "Establish and apply rules for the secure development of software and systems."),
    ("A.8.26", TECHNOLOGICAL, "Application security requirements", PREVENTIVE,
     "Identify, specify and approve security requirements when developing applications."),
    ("A.8.27", TECHNOLOGICAL, "Secure system architecture and engineering principles", PREVENTIVE,
     "Establish and apply secure engineering principles to system development."),
    ("A.8.28", TECHNOLOGICAL, "Secure coding", PREVENTIVE,
     "Apply secure coding principles to software development."),
    ("A.8.29", TECHNOLOGICAL, "Security testing in development and acceptance", PREVENTIVE,
     "Define and implement security testing processes in the development lifecycle."),
    ("A.8.30", TECHNOLOGICAL, "Outsourced development", PREVENTIVE,
     "Direct, monitor and review activities related to outsourced system development."),
    ("A.8.31", TECHNOLOGICAL, "Separation of development, test and production environments", PREVENTIVE,
     "Separate and secure development, test and production environments."),
    ("A.8.32", TECHNOLOGICAL, "Change management", PREVENTIVE,
     "Subject changes to information processing facilities to change management procedures."),
    ("A.8.33", TECHNOLOGICAL, "Test information", PREVENTIVE,
     "Appropriately select, protect and manage information used for testing."),
    ("A.8.34", TECHNOLOGICAL, "Protection of information systems during audit testing", PREVENTIVE,
     "Plan and agree audit tests involving operational systems to minimise disruption."),
]

# ISO/IEC 27001:2022 mandatory clauses 4-10 and the documented information
# each one requires. This drives the "ISMS Clauses" checklist.
CLAUSES = [
    ("4.1", "Understanding the organisation and its context",
     "Determine external and internal issues relevant to the ISMS."),
    ("4.2", "Needs and expectations of interested parties",
     "Identify interested parties and their information security requirements."),
    ("4.3", "Determining the scope of the ISMS",
     "Documented information: the ISMS scope statement."),
    ("4.4", "Information security management system",
     "Establish, implement, maintain and continually improve the ISMS."),
    ("5.1", "Leadership and commitment",
     "Top management demonstrates leadership and commitment to the ISMS."),
    ("5.2", "Policy",
     "Documented information: the information security policy."),
    ("5.3", "Organisational roles, responsibilities and authorities",
     "Assign and communicate responsibilities and authorities for the ISMS."),
    ("6.1.1", "Actions to address risks and opportunities",
     "Determine risks and opportunities that need to be addressed."),
    ("6.1.2", "Information security risk assessment",
     "Documented information: the risk assessment process."),
    ("6.1.3", "Information security risk treatment",
     "Documented information: risk treatment process and Statement of Applicability."),
    ("6.2", "Information security objectives and planning",
     "Documented information: measurable information security objectives."),
    ("6.3", "Planning of changes",
     "Changes to the ISMS are carried out in a planned manner."),
    ("7.1", "Resources",
     "Determine and provide resources needed for the ISMS."),
    ("7.2", "Competence",
     "Documented information: evidence of competence of personnel."),
    ("7.3", "Awareness",
     "Personnel are aware of the policy and their contribution to the ISMS."),
    ("7.4", "Communication",
     "Determine internal and external communications relevant to the ISMS."),
    ("7.5", "Documented information",
     "Create, update and control documented information required by the ISMS."),
    ("8.1", "Operational planning and control",
     "Documented information: confidence that processes are carried out as planned."),
    ("8.2", "Information security risk assessment (operation)",
     "Documented information: results of information security risk assessments."),
    ("8.3", "Information security risk treatment (operation)",
     "Documented information: results of information security risk treatment."),
    ("9.1", "Monitoring, measurement, analysis and evaluation",
     "Documented information: evidence of monitoring and measurement results."),
    ("9.2", "Internal audit",
     "Documented information: the audit programme and audit results."),
    ("9.3", "Management review",
     "Documented information: results of management reviews."),
    ("10.1", "Continual improvement",
     "Continually improve the suitability, adequacy and effectiveness of the ISMS."),
    ("10.2", "Nonconformity and corrective action",
     "Documented information: nature of nonconformities and results of corrective action."),
]
